/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package takesix;

import com.google.common.collect.ImmutableMap;
import takesix.api.Player;
import takesix.api.PlayerId;
import takesix.players.RandomPlayer;

import java.util.Map;

public class App {
    public static void main(String[] args) {
        Map<PlayerId, Player> players = ImmutableMap.of(
                PlayerId.of("player1"), new RandomPlayer(),
                PlayerId.of("player2"), new RandomPlayer(),
                PlayerId.of("player3"), new RandomPlayer()
        );
        Engine engine = new Engine(players);
        engine.run();
    }
}
